# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-02 21:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('title', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('pub_date', models.DateTimeField(verbose_name='Publish date')),
                ('file', models.CharField(max_length=20, null=True, unique=True)),
            ],
            options={
                'ordering': ['pub_date'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Comment content')),
                ('vote', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2017, 6, 2, 21, 51, 29, 274527, tzinfo=utc), verbose_name='Comment date')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Article')),
            ],
            options={
                'ordering': ['article'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('article', models.ManyToManyField(to='blog.Article')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True, verbose_name='e-mail')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='visitor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Visitor'),
        ),
    ]
