# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20151105093325 on 2017-01-22 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(verbose_name='Blog content')),
                ('pub_date', models.DateTimeField(verbose_name='Date')),
            ],
        ),
    ]
