# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-07 22:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170607_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 7, 22, 56, 22, 366248, tzinfo=utc), verbose_name='Comment date'),
        ),
    ]
