# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-04 21:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170607_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 4, 21, 41, 12, 961584, tzinfo=utc), verbose_name='Comment date'),
        ),
    ]
