# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-04 21:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20170704_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 4, 21, 43, 22, 601390, tzinfo=utc), verbose_name='Comment date'),
        ),
    ]
